// Wiegand Alpine Coasters
export default [
  "Aerie's Alpine Coaster",
  'Alavi Park Sled',
  'Allgäu Coaster',
  'Allwetterbobbahn',
  'Alpbachtaler Lauser Sauser',
  'Alpesibob',
  'Alpin Bob',
  'Alpine Coaster',
  'Alpine-Coaster',
  'Alpine-Coaster-Bahn',
  'Alpine Coaster Dittrichshütte',
  'Alpine Hills',
  'Alpine Mountain Coaster',
  'Alpine Racer',
  'Alpsee Coaster',
  'Alpspitz Coaster',
  'AltmühlBOB',
  'Arena Coaster',
  'Bärenbob',
  'Bayerwald-Coaster',
  'Berta',
  'Black Viper',
  'Blomberg-Blitz',
  'Bob',
  'Bobbahn',
  'Bob-Bahn',
  'Bob-Luge',
  'Bob na Šinama',
  'Boboffka',
  'Bobová Dráha',
  'Bobovka',
  'Bob Pálya',
  'Bobpálya',
  'Bobsled Ride',
  'Bobsleigh',
  'Bob su rotaia',
  'Bob su Rotaia',
  'Bob Su Rotaia',
  'BocksBergBob',
  'Breathtaker',
  'Brocken Coaster',
  'Canyon Coaster',
  'Chiemgau Coaster',
  'Coaster at Goats on the Roof',
  'Coasterbahn',
  'Coaster Bob',
  'Coaster Ochsenkopf',
  'Comète',
  'Copperhead Mountain Coaster',
  'Cowboy Coaster',
  'Crazy Toboggan',
  'Dağ Kızağı',
  'Dağ Kizaği',
  'Dongtian Flying Dragon',
  'Double High Speed Alpine Coaster',
  'Drachenflitzer',
  "Dragon's Tail Coaster",
  'Eibl Jet Türnitz',
  'Eifel-Coaster',
  'Erdei Bob',
  'Extreme Sleds',
  'Fairy Knights',
  'Family Bob',
  'Fast Coaster',
  'Feeblitz',
  'Fforest Coaster',
  'Forest Flyer',
  'Forest Slide',
  'Frankenbob',
  'Fröschbrunna Coaster',
  'Georgia Mountain Coaster',
  'German Toboggan',
  'Glade Runner',
  'Gold Runner Alpine Coaster',
  'Gravity Slide',
  'Harzbob',
  'Hasenhorn Coaster',
  'Hellbender',
  'Hexenexpress',
  'Höllen Coaster',
  'Horská Bobová Dráha',
  'Hua-Wiecoaster',
  'Inselrodelbahn Bergen',
  'Jais Sledder',
  'JungelBob',
  'Jungle Coaster',
  'Jungle Leap',
  'Klausberg Flitzer',
  'Kolejka Górska',
  'Kolejka Górska Adrenaline',
  'Kronberg-Bobbahn',
  'Kurpfalz-Coaster',
  'Lucky Flitzer',
  'Luge',
  'Luge 4 Saisons',
  'Luge Alpine',
  'Luge-Alpine Coaster',
  'Luge des Cimes',
  'Luge Dévale',
  'Luge du Caribou',
  'Luge Féeline',
  "Luge L'Orrian Express",
  'Luge Molines Sensation',
  'Luge Sur Rail',
  'Luge sur Rail',
  'Luge Sur Rails',
  'Luge Toutes Saisons',
  'Màgic Gliss',
  'Maisiflitzer',
  'Mamutí Horská Dráha',
  'Mátra Bob',
  'Mineshaft Coaster',
  'Monte Coaster',
  'Moonshine Mountain Coaster',
  'Moselbob',
  'Mountain Coaster',
  'Mountain-Luge',
  'Mountain Slides',
  'Mountain Twister',
  'Mustang Mountain Coaster',
  'Nocky Flitzer',
  "Nor'easter Mountain Coaster",
  'Norma Loops',
  'Odenwaldbob',
  'Osttirodler',
  'Outlaw Mountain Coaster',
  'Panorama Track',
  'Pista Bob',
  'Pista Bob Lorica',
  'Pista de bob',
  'Praloops',
  'Rhönbob',
  'Ridge Rider Mountain Coaster',
  'Ridge Runner Mountain Coaster',
  'RILA Fun Park',
  "Ripley's Mountain Coaster ",
  'Rittisberg Coaster',
  'Rocky Top Mountain Coaster',
  'Rodelbahn',
  'Rodelbahn Floomzer',
  'Rodelban',
  'Rodelbana',
  'Rushmore Mountain Coaster',
  'Samurai Slide',
  'Sankališče Zlodejevo',
  'Scaly Screamer',
  'Schanzen Wirbel',
  'Scharmützelbob',
  'Schlitte Mountain',
  'Schneisenfeger',
  'Schöne Aussicht',
  'Shahdag Coaster',
  'Silbersee Bob',
  'Ski&Sun Coaster',
  'Sky High Mountain Coaster',
  'Slideway',
  'Slittinovia',
  'Sommerrodelbahn',
  'Speed Track',
  'Speed Dragoz: La Luge Des Carroz',
  'Speed Fun',
  'Speed Luge',
  'Steirarodl',
  'Sternrodler',
  'The Branson Coaster',
  'Timber Ripper Mountain Coaster',
  'Timber Twister',
  'Timoks Coaster',
  'Tobogan',
  'Toboggan',
  'Toboggan Run',
  'Tobotronc',
  'Trapper Slider',
  'Trenó',
  'Tricky Track',
  'Trineo Ruso',
  'Tulawaka',
  'Tumwater Twister',
  'Tunnel Track',
  'Verdon Express',
  'Via Lattea',
  'Viking',
  'Wilderness Run Alpine Coaster',
  'Wild Stallion',
  'Wiz Luge',
  'Xe Trượt Núi',
  'Youhooo!',
] as const;
