// Vekoma SLC's
export default [
  'Arkham Asylum - Shock Therapy',
  'Batman The Ride',
  'Blackout',
  'Blue Tornado',
  'Cobra',
  'Condor',
  'Death Rail',
  'Desafío',
  'Dragon in Clouds',
  'Dream Thunder',
  "Ednör - L'Attaque",
  'F² Fright Flight',
  'Firewhip',
  'Flight Deck',
  'Gauntlet',
  'Golden Wings over the Snowfield',
  "Great Nor'Easter",
  'Hangman',
  'Hurricane',
  'Infusion',
  'Jaguar',
  'Kong',
  'Kumali',
  'Kumba',
  'Limit',
  'Mayan Adventure',
  'Mind Eraser',
  'MP-Xpress',
  'Nio',
  'Nopuko Air Coaster',
  'Odyssey',
  'Pusing Lagi',
  'Queen Cobra',
  'Raptor',
  'Riddler Revenge',
  'Roller Coaster',
  'Roller Coaster Mayan',
  'Serial Thriller',
  'Snow Mountain Flying Dragon',
  'Suspended Looping Coaster',
  'T3',
  'Thunderhawk',
  'Titánide',
  'Traumatizer',
  'Twisted Typhoon',
] as const;
