// Arrow & Vekoma MK-1200
export default [
  'Anaconda',
  'Apocalypse',
  'Balagos - Flying Flame',
  'Bat',
  'Big Dipper',
  'Big Loop',
  'Black Hole Express',
  'Blue Hawk',
  'Bocaraca',
  'Boomerang',
  'Boomerang Challenge Coaster',
  'Boomerang Coast to Coaster',
  'Boomerang Hyper Coaster',
  'Boomerang-Roller Coaster',
  'Bumerang',
  'Búmeran',
  'Canobie Corkscrew',
  'Canyon Blaster',
  'Carolina Cyclone',
  'Chicago Loop',
  'Cobra',
  'Coca-Cola Roller',
  'Colossus',
  'Cork Screw',
  'Corkscrew',
  'Crazy Roller Coaster',
  'Demon',
  'Double Loop',
  'Drachen Fire',
  'Dragon Fyre',
  'Dragon Mountain',
  'EuroLoop',
  'Extremeroller',
  'Fantasia Special',
  'Flashback',
  'Fluch des Kraken',
  'Flying Cobras',
  'Flying Tiger',
  'French Revolution2 VR',
  'Generator',
  'Gold Coaster',
  'Goudurix',
  'Great American Scream Machine',
  'Head Spin',
  'Jolly Rancher Remix',
  'Kamikaze',
  'Korkkiruuvi',
  'Loch Ness Monster',
  'Loopen',
  'Mega Looping Bahn',
  'Millennium',
  'Miralooping',
  'Missile',
  'Montanha Espacial',
  'Montaña Rusa',
  'Ninja',
  'Orient Express',
  "Phantom's Revenge",
  'Python',
  "Ragin' Cajun",
  'Recoil',
  'Roller Coaster',
  'Rolling X-Train',
  'Scream Machine',
  'Screamer',
  'Screw Coaster',
  'Sea Serpent',
  'Shaman',
  'Shockwave',
  'Space Shuttle',
  'Speed of Sound',
  'SpeedSnake FREE',
  'Spiral',
  'Star Mountain',
  'Stress Express',
  'Super Manège',
  'Super Spirale',
  'Super Tornado',
  'Super Wirbel',
  'Tennessee Tornado',
  'The Dragon',
  'Thunderbolt',
  'Tidal Wave',
  'Time Twister',
  'Titan',
  'Tornado',
  'Vampire',
  'Viper',
  'Vortex',
  'Wabash Cannonball',
  'Wervelwind',
  'Whirl Wind Looping Coaster',
  'Whirlwind',
  'Whirly Roller Coaster',
  'Wipeout',
] as const;
