// Intamin Mega/Giga/Accelerator
export default [
  'All Speeds',
  'Cheetah Hunt',
  'Coaster Through the Clouds',
  'Desert Race',
  'Expedition GeForce',
  'Fly Over Mediterranean',
  'Formula Rossa',
  'Goliath',
  'Hyperion',
  'ISpeed',
  'Intimidator 305',
  'Kanonen',
  'Kawasemi',
  'Kingda Ka',
  'Kondaa',
  'Light Of Revenge',
  'Light Speed',
  'Matugani',
  'Maverick',
  'Mega-Lite',
  'Millennium Force',
  'Nefeskesen',
  'Pantheon',
  'Piraten',
  'Red Fire',
  'Ride of Steel',
  'Rita',
  'Senzafiato',
  'Skycar',
  'Speed Monster',
  'Stealth',
  'Steel Dolphin',
  'Storm Runner',
  'Superman - Ride Of Steel',
  'Superman Escape',
  'Superman the Ride',
  'Taiga',
  'Taron',
  'Thunder Dolphin',
  'Top Thrill Dragster',
  'Toutatis',
  'Xcelerator',
  'Zaturn',
] as const;
