// B&M Hyper & Giovanola Hyper
export default [
  "Apollo's Chariot",
  'Behemoth',
  'Candymonium',
  'Diamondback',
  'Flight of the Himalayan Eagle Music Roller Coaster',
  'Fury 325',
  'Goliath',
  'Hollywood Dream: The Ride',
  'Leviathan',
  'Mako',
  'Nitro',
  'Orion',
  'Raging Bull',
  'Shambhala',
  'Silver Star',
  'Titan',
  'Thunder Striker',
];
