// B&M Inverted
export default [
  'Afterburn',
  'Alpengeist',
  'Banshee',
  'Batman The Ride',
  'Batman: The Ride',
  'Black Mamba',
  'Diavlo',
  'Dragon Challenge',
  'Flight Deck',
  'Gambit',
  'Goliath',
  'Great Bear',
  'Great White',
  'Katun',
  'Lightning',
  'Monster',
  'Montu',
  'Nemesis',
  'Nemesis Inferno',
  'Orochi',
  'OzIris',
  'Patriot',
  'Phaethon',
  'Pyrenees',
  'Raptor',
  'Shadows of Arkham',
  'Silver Bullet',
  'Talon',
  'Vampire',
] as const;
