// Zierer tivoli
export default [
  'Achtbaan',
  'Achterbahn',
  'Alap Alap',
  'Autosled',
  'Avonturenslang',
  'Barnstormer',
  'Bayou Express',
  'Beaver Land Mine Ride',
  'Big Apple',
  'Boardwalk Canyon Blaster',
  'Buccaneer Bay Bullet',
  'Bullet',
  'Buzz Coaster',
  'Catarina',
  'Catariños',
  'Cat-O-Pillar Coaster',
  "Catwoman's Whip",
  'Children Coaster',
  'Choconoy',
  'Chura Racer',
  'Cirkusexpressen',
  'Cobra',
  'Coccinelle',
  'Colorado Express',
  'Dino Chase',
  'Drako',
  'Egg-Spress',
  'Eiserne Schlange',
  'Endicott Emerald Mine',
  'Familienachterbahn',
  'Family Coaster',
  'Field Runner',
  'Firefly Roller Coaster',
  'Flinker Fridolin',
  'Froschbahn',
  'Ghoster Coaster',
  'Green Scream',
  'Green Snake',
  'Harley Quinn Crazy Train',
  'Holzwurmachterbahn',
  'Hoot N Holler',
  'Huracan',
  'Jaguar!',
  'Kaninus',
  'Karavanen',
  'Keverbaan',
  'Kiddie Coaster',
  'Kiddy Coaster',
  'Kikkerachtbaan',
  'Kombo',
  'Ladybird',
  'Lady Bird',
  'Lady Bug Coaster',
  'Leppäkerttujuna',
  '#LikeMe Coaster',
  'Linie 88',
  'Live Oak Ladybug',
  'Mariehønen',
  'Marienkäferbahn',
  'Marienkäfer Hochbahn',
  'New Roller Coaster',
  'Nyckelpigan',
  'Orca Ride',
  'Pepsi Orange Streak',
  'Puff the Little Fire Dragon',
  'Rampage',
  'Rasender Tausendfüßler',
  'Rattlesnake Coaster',
  'Reindeer Coaster',
  'Roller Coaster',
  'Ronde des Rondins',
  "Rudy's Rapid Transit",
  'Seeschlange',
  'Serpent Hopi',
  'Silver Streak',
  'SOS Numérobis',
  'Tarzungle',
  'Tentomushi',
  'Timber Ride',
  'Timber Twister',
  'Tivoli Coaster',
  'Tom y Jerry',
  'Treetops Rollercoaster',
  'Tsunami',
  'Vauhtimato',
  'Vigía',
  'Viktor Vandorm',
  'Wild West Express',
  'Zeeslang',
] as const;
