// Schwarzkopf looping coasters
export default [
  'Aconcagua',
  'All American Triple Loop',
  'BMRX',
  'Big Blue',
  'Bullet',
  'Cascabel 2.0',
  'Colossus',
  'Colossus the Fire Dragon',
  'Death Train',
  'Double Loop',
  'Golden Loop',
  "Greased Lightnin'",
  "Greezed Lightnin'",
  'Gwazi',
  'Jet Scream',
  'Jetline',
  'Katapul',
  'Katapult',
  'Katapulta',
  'Katapultti',
  'King Kobra',
  'Knightmare',
  'Laser',
  'Laser Loop',
  'Lasso Loop',
  'Lisebergbanan',
  'Lisebergs Loopen',
  'Looping Star',
  'Magnum Force',
  'Mindbender',
  "Montezooma's Revenge",
  'Nessie',
  'New Revolution',
  'Psyké Underground',
  'Quimera',
  'Revolution',
  'Riddler Mindbender',
  'Scorpion',
  'Shock Wave',
  'Shuttle Loop',
  'Silberpfeil',
  'Silver Bullet',
  'Sooperdooperlooper',
  'Teststrecke',
  'Texas Tornado',
  'Thriller',
  'Thunder Loop',
  'Thunder Loop Express',
  'Thunderlooper',
  'Tidal Wave',
  'Tower of Terror',
  'Triple Loop Coaster',
  'Tsunami',
  'Twist and Shout',
  'Vertigo',
  'Viper',
  "White Lightnin'",
  'Wiener Looping',
  'Zonga',
] as const;
