// Vekoma and Arrow Mine trains
export default [
  'Adventure Express',
  'Big Bad John',
  'Big Thunder Mountain',
  'Calamity Mine',
  'Canyon Blaster',
  'Carolina Goldrusher',
  'Cedar Creek Mine Ride',
  'Choco Chip Creek',
  'Colorado Adventure',
  'Dahlonega Mine Train',
  'Diablo - Tren de la Mina',
  'Diamond Devil Run',
  'Dragon in Snowfield',
  'Excalibur',
  'Gold Rusher',
  'Iron Horse',
  'Jungle Racing',
  'Lost Valley',
  'Mammut',
  'Mine Adventure',
  'Mine Coaster',
  'Olandese Volante',
  'Port of Sky Treasure',
  'River King Mine Train',
  'Road Runner Express',
  "Rock n' Roller Coaster",
  'Runaway Mine Train',
  'Thunder Express',
  'Thunderation',
  'Trailblazer',
  'Tren Minero',
  'Yagiyama Cyclone',
] as const;
