// mack powered
export default [
  'Alpen Express',
  'Alpenexpress Enzian',
  'Apache Whirlwind',
  'Arctic Blast',
  'Blauer Enzian',
  'Bob Express',
  'Carrara',
  'Draak',
  'Dragen',
  'Dynamite Express',
  'Eurospeed',
  'Expreso Minero',
  'Flying Fish',
  'Galaxie Express',
  'Gletscherblitz',
  'Gobbi Express',
  'Gods of Egypt - Battle for Eternity',
  'Gold Mine Train',
  'Grottenblitz',
  'Gruvbanan',
  'Idän Pikajuna',
  'Kansas City-Express',
  'Le Dragon des Sortilèges',
  'Mælkevejen',
  'Max + Moritz',
  'Miniwah',
  'Odinexpressen',
  'Pikajuna',
  'Rothaarblitz',
  'Runaway Mine Train',
  'Runaway Train',
  'Scorpion Express',
  'Silverpony Express',
  'Spreeblitz',
  'Super Train Tokaido',
  'Thunder Run',
  'Tokaido Express',
  'T-Rex Family Coaster',
];
