export default [
  'Bergbana',
  'Bergbanan',
  'Big Dipper',
  'Blue Streak',
  'Bobsleighbanan',
  'Bowler Dip',
  'Brownie Coaster',
  'Canadian Toboggan',
  "Casey's Coaster",
  'Chase through the Clouds',
  'Coaster',
  'Comet',
  'Dazy Dazer',
  'Derby Racer',
  'Dipper',
  'Dips',
  'Dips Coaster',
  'Dip The Dips',
  'Dixie Flyer',
  'Double Eight Toboggan Railway',
  'Dragon Mountain Scenic',
  "Ex Charles Thurston's Scenic",
  'Figure 8',
  'Figure-8',
  'Figure 8 Toboggan',
  'Figure Eight',
  'Figure Eight Railway',
  'Figure Eight Toboggan',
  'Figure of Eight',
  'Figuur 8 baan',
  'FireFly',
  'Flying Toboggan',
  'Forest Ride',
  'Forest Toboggan',
  'Giant Coaster',
  'Giant Coaster Dips',
  'Giant Racer',
  'Giant Safety Coaster',
  'Gravity Road',
  'Great Figure 8',
  'Great Mountain Ride',
  'Great Roller Bowler Coaster',
  'Great Thriller',
  'Green Streak',
  'Greyhound',
  'Hochschaubahn',
  'Huit Volant',
  'Island Roller Coaster',
  'Jack Rabbit',
  'Jollier',
  'Kiddie Coaster',
  'Kolejka Górska',
  'Leap Frog',
  'Leap The Dips',
  'Leap the Dips',
  'Loop the Dip',
  'Mammoth Roller Coaster',
  'Mammoth Velvet Coaster',
  'Monroe Roller Coaster',
  'Montaña Rusa',
  'Montana Rusa',
  'Mountain Speedway',
  'Racer',
  'Racing Coaster',
  'Racing Derby',
  'Reverser',
  'Roller Coaster',
  'Rolo Coaster',
  'Royal Dip Coaster',
  'Royal Giant Dips',
  'Runaway Coaster',
  'Rutschebanen',
  'Scenic',
  'Scenic Railway',
  'School of Mines',
  'Sky Rocket',
  'Slope Car',
  'Slope Shooter',
  'Steel Stella',
  'Swing Coaster',
  'Thriller',
  'Tickler',
  'Toboggan',
  'Toboggan Slide',
  'Toboggan slide',
  'Triple Eight',
  'Triple Figure Eight',
  'Tyrolean Tubtwist',
  'Velvet Toboggan',
  'Vuoristorata',
  'Whirl Pool Dips',
  'Whizzer',
  'Wiz',
] as const;
