// Mack Wild Mouse, Maurer Söhne
export default [
  'Apple Zapple',
  'Coast Rider',
  'Crazy Mine',
  'Dark Knight',
  'Das Große LEGO Rennen',
  "Descente en Schlitt'",
  'Fly',
  'Flying Dutchman Gold Mine',
  'Ghost Chasers',
  'Go Bananas!',
  "Goofy's Sky School",
  'Gotham City Gauntlet Escape from Arkham Asylum',
  'Great Lego Race',
  "Holly's Wilde Autofahrt",
  'Jungle Coaster',
  'Kopermijn',
  "Käpt'n Jack's Wilde Maus",
  'Marble Madness',
  'Matterhorn Blitz',
  'Rat',
  'Rattlesnake',
  'Ricochet',
  'Road Runner Express',
  'SandSerpent',
  'Scooby-Doo Spooky Coaster Next Generation',
  'Sharolet',
  'Souris folle',
  'Speedy Bob',
  'Speedy Nuts',
  'Technic Coaster',
  'Tiger Express',
  'Vilde Mus',
  'Vértigo',
  'Wild Maus',
  'Wild Mouse',
  'Wilde Maus',
  'X-treme Racers',
  'Zig Zag',
] as const;
