// B&M Sit-down, Floorless & Stand-up
export default [
  'Batman - The Dark Knight',
  'Chang',
  'Decepticoaster',
  'Dominator',
  'Dragon Khan',
  "Dragon's Run",
  'Dæmonen',
  'Firebird',
  'Georgia Scorcher',
  'Green Lantern',
  'Hair Raiser',
  'Hot Wheels Nitro',
  'Hydra the Revenge',
  'Incredible Hulk',
  'Insane Speed',
  'Iron Wolf',
  'Kraken',
  'Kumba',
  'Medusa',
  'Patriot',
  "Riddler's Revenge",
  'Rougarou',
  'Scream!',
  'Superman / la Atracción de Acero',
  'Superman Krypton Coaster',
  'Time Machine',
  'Vortex',
  'Wildfire',
] as const;
