// Removed the topper track RMC's as they are better served with the RMC coaster type.
// There are some misplaced names in here, like side friction and wild mouses
export default [
  'Achterbahn',
  'Aerial Subway',
  'Aero Dips',
  'Airplane Coaster',
  'Alpine Dips',
  'Alpine Racer',
  'Alpine Roadway',
  'Alpine Scenic Railway',
  'Alps',
  'American Eagle',
  'American Thunder',
  'Anaconda',
  'Animal Coaster',
  'Antelope',
  'Apocalypse the Ride',
  'Ariel Railway',
  'Arkansas Twister',
  'Aska',
  'Atom Smasher',
  'Auto BergBahn',
  'Avalanche',
  'Baby Dipper',
  'Baby Wildcat',
  'Backety-Back Scenic Railway',
  'Balder',
  'Bandit',
  'Beach Coaster',
  'Bear Cat',
  'Beast',
  'Beastie',
  'Ben Hur Racer',
  'Ben Hur Roller Coaster',
  'Berg och dalbanan',
  'Berg- und Talbahn',
  'Big Beast',
  'Big Dipper',
  'Big Roller Coaster',
  'Big Scenic Railway',
  'Blarney Racer',
  'Blue Flyer',
  'Blue Streak',
  'Blue Streak Racer',
  'Boardwalk Bullet',
  "Bob's",
  'Bobs',
  'Bob Sled Dipper',
  'Bombay Express',
  'Bomber',
  'Boss',
  'Boulder Dash',
  'Bowls of Joy',
  'Breezer',
  'Brown Flyer',
  'Bullet',
  'Bush Beast',
  'Canadian Topsy Turvy Railway',
  'Cannon Ball',
  'Cannon-Ball',
  'Cannonball',
  'Cannonball Run',
  'Cannon Coaster',
  'Centrifugal Railway',
  'Chase through the Clouds',
  'Chase Through The Clouds',
  'Cheetah',
  'Chemin de Fer Scénique',
  'Circle Dip',
  'Circle Dips',
  'Circular Gravity Railway',
  'Classic Coaster',
  'Coal Mine & Additional Scenic Ride',
  'Coaster',
  'Coaster Dips',
  'Coaster Express',
  'Coaster Flyer',
  'Coastersaurus',
  'Coasting Thru Switzerland',
  'Coliseum Coaster',
  'Colossos - Kampf der Giganten',
  'Colossus',
  'Comet',
  'Comet Coaster',
  'Comet Jr.',
  'Coney Island Switchback Railroad',
  'Cornball Express',
  'Crazy Car Coaster',
  'Crystal Flyer',
  'Cú Chulainn',
  'Cupid Coaster',
  "Cupid's Coaster",
  'Cyclone',
  'Cyclone Bowls',
  'Cyclone Racer',
  'Cyclops',
  'Dania Beach Hurricane',
  'Dark Tunnel Coaster',
  'Dauling Dragon',
  'Dazy Dazer',
  'Dazy Dazier Dip Coaster',
  'Deep Dip Coaster',
  'Deep-Dip Coaster',
  'Deep Dipper',
  'Deep Dip Racer',
  'Deep Dips',
  'Derby',
  'Derby Racer',
  'Detroit Bobs',
  'Devil',
  "Devil's Backbone",
  "Devil's Chute",
  "Devil's Coach",
  "Devil's Gorge",
  'Dip',
  'Dip Coaster',
  'Dipper',
  'Dips',
  'Dips Coaster',
  'Dip the Dips',
  'Dip The Dips',
  'Dip-the-Dips',
  'Dip-The-Dips',
  'Dip the Dips Scenic Railway',
  'Dixie Flyer',
  'Dragon Coaster',
  'Dragon Gorge',
  'Dragon Gorge Scenic Railroad',
  'Einschienenbahn',
  'Elevated Scenic Railway',
  'Elf',
  'El Toro',
  'Excalibur',
  'Exposition Flyer',
  'Express',
  'Falken',
  'Figure 8',
  'Figure-8',
  'Figure 8 Toboggan',
  'Figure Eight',
  'Figure Eight ',
  'Figure Eight Railway',
  'Figure Eight Toboggan',
  'Figure of Eight',
  'Figuur 8 baan',
  'Fireball',
  'Fjord Flying Dragon',
  'Flash',
  'Flip Flap Railway',
  'Florida Hurricane',
  'Flugbahn',
  'Flyer',
  'Flyer Comet',
  'Flying Cloud',
  'Flying Dragon',
  'Flying Toboggan',
  'Forest Coaster',
  'Forest Ride',
  'Gaint Dip Slide',
  'Gebirgsbahn',
  'Gebirgsbahn 1',
  'Gebirgsbahn 2',
  'Gebirgsszeneriebahn',
  'Gee Whizz Dip the Dips',
  'Gee Wiz',
  'Georgia Cyclone',
  'Ghoster Coaster',
  'GhostRider',
  'Giant',
  'Giant Auto Dip',
  'Giant Blue Streak Coaster',
  'Giant Coaster',
  'Giant Coaster ',
  'Giant Coaster Dips',
  'Giant Dip',
  'Giant Dipper',
  'Giant Flyer',
  'Giant Racer',
  'Giant Roller Coaster',
  'Giant Safety Coaster',
  'Giant Skyrocket',
  'Gold Striker',
  'Gorge Ride',
  'Grand Canyon',
  'Grand Canyon Scenic Railroad',
  'Grand National',
  'Grand Scenic Railway',
  "Grant's Coaster",
  "Grant's Russian Toboggan Slide",
  'Gravity Pleasure Switch Back Railway',
  'Gravity Railway',
  'Gravity Road',
  'Gravity Scenic Railway',
  'Great American Scream Machine',
  'Great Derby',
  'Great Desert-Rally',
  'Great Figure 8',
  'Great Mountain Ride',
  'Great Roller Bowler Coaster',
  'Great Scenic Railway',
  'Great Thriller',
  'Great White',
  'Green Dragon',
  'Green Streak',
  'Grey Fox',
  'Greyhound',
  'Griffiths Scenic Railway',
  "Griffith's Scenic Railway",
  'Grizzly',
  'Gwazi',
  'Hades 360',
  'Heidi The Ride',
  'Hell Cat',
  'Hercules',
  'High Frolics',
  'High Roller',
  'Himalaya',
  'Himalaya Railway',
  'Hochbahn',
  'Hochschaubahn',
  'Hoosier Hurricane',
  'Huit Volant',
  'Hullámvasút',
  'Hummer',
  'Humming Bird',
  'Hummingbird',
  'Hurler',
  'Hurricane',
  'Hydraulic Dive',
  'Ingersol Toboggan Railroad',
  'InvadR',
  'Island Flyer',
  'Island Roller Coaster',
  'Jack Rabbit',
  'Jack Rabbit Racer',
  'Jazz Railway',
  "Jerome's Wooden Dragon",
  'Jet Star',
  'Jetstream',
  'Jollier',
  'Joris en de Draak',
  'Judge Roy Scream',
  'Jumper',
  'Jungle Trailblazer',
  'Junior Coaster',
  'Junior Speedway',
  'Junior Wild Cat',
  'Jupiter',
  'Kentucky Flyer',
  'Kentucky Rumbler',
  'Kentucky Thoroughbred',
  'Kiddie Bobs',
  'Kiddie Coaster',
  'Kiddie Dips',
  'Kiddie Roller Coaster',
  'Kiddy Coaster',
  'Kids Coaster',
  'King Bee',
  'Kingdom Coaster',
  "King Solomon's Mines",
  'Kolejka Górska',
  'L.A. Thompson Scenic Railway',
  'Leap Frog',
  'Leaping Giant',
  'Leap the Dip',
  'Leap The Dips',
  'Leap the Dips',
  'Legend',
  'Leviathan',
  'Lightning',
  'Lightning Racer',
  "Lil' Dipper",
  'Limit',
  'Little Dipper',
  'Loop-de-Loop',
  'Loopingbahn',
  'Loop the Dip',
  'Loop the Loop',
  'Loop The Loop',
  'Lost Coaster of Superstition Mountain',
  'Loup-Garou',
  "Lover's Tub",
  'Luna-Bahn',
  'Mad Mouse',
  'Mad Racers',
  'Magnus Colossus',
  'Mammoth Comet Coaster',
  'Mammoth Figure 8',
  'Mammoth Racing Coaster',
  'Mammoth Roller Coaster',
  'Mammoth Velvet Coaster',
  'Mammut',
  'Mean Streak',
  'Medusa',
  'Megafobia',
  'Mega Zeph',
  'Meteor',
  'Mighty Canadian Minebuster',
  'Mile Sky Chaser',
  'Million Dollar Coaster',
  'Mine Blower',
  'Monroe Roller Coaster',
  'Monstre',
  'Montagne Russa',
  'Montaña Rusa',
  'Montana Rusa',
  'Montanha Russa',
  'Montezum',
  'Mountain Caterpillar Railway',
  'Mountain Dip',
  'Mountain Flyer',
  'Mountain Railway',
  'Mountain Scenic Railway',
  'Mountain Speedway',
  'Mr. Twister',
  'Mystic Timbers',
  'New Derby Racer',
  'New Mexico Rattler',
  'New Wilder Wild Mouse',
  'Niagara-Wasserbahn',
  'Nickelodeon Streak',
  'Nightmare',
  'North Wind Coaster',
  'Ocean Roller Coaster',
  'Oriental Ride',
  'Original Wild Mouse',
  "Oscar's Wacky Taxi",
  'Outlaw',
  'Over The Rockies',
  'Over The Top',
  'Ozark Wildcat',
  "Peck's Prancing Ponies",
  'Pegasus',
  'Phantastic Coaster',
  'Phoenix',
  'Pikes Peak Scenic Railway',
  'Pippin',
  'Pirun Kelkka',
  'Predator',
  'Prowler',
  'Psyclone',
  'Python in Bamboo Forest',
  'Racer',
  'Racer 75',
  'Racer Dip',
  'Racer Dips',
  'Race Thru The Clouds',
  'Racing Coaster',
  'Racing Derby',
  'Racing Whippet',
  'Radio Streak',
  'Raging Wolf Bobs',
  'Railway',
  'Rampage',
  'Rattler',
  'Raven',
  'Ravine Flyer',
  'Ravine Flyer II',
  'Red Devil',
  'Red Streaker',
  'Regina II',
  'Renegade',
  'Reverser',
  'Roar',
  'Roaring Timbers',
  'Roar-O-Saurus',
  'Robin Hood',
  'Rocket',
  'Rodelbahn',
  'Roller Boller Coaster',
  'Roller Coaster',
  'Roller Dip',
  'Roller Dips Coaster',
  'Rolling Thunder',
  'Rollo Coaster',
  'Rolo Coaster',
  'Round the Treetops',
  'Royal Ascot Racer',
  'Royal Dip Coaster',
  'Royal Giant Dips',
  'Royal Giant Dips Coaster',
  'Royal Gorge',
  'Royal Gorge Scenic Railway',
  'Royal Yorkshire Switchback',
  'Runaway Coaster',
  'Runaway Mine Train',
  'Rutschbahn',
  'Rutschebanen',
  'Scamper',
  'Scenic',
  'Scenic Auto-Dip',
  'Scenic Railroad',
  'Scenic Railway',
  'Scenic Railway ',
  'Scenic Switchback Railway',
  'School of Mines',
  "Screamin' Eagle",
  "Screechin' Eagle",
  'Screem Machine',
  'Sea Dragon',
  'Sea Serpent',
  'Serpentine Railway',
  'Shivering Timbers',
  'Shooting Star',
  'Shooting the Dips',
  'Sidewinder',
  'Sierra Tonante',
  'Silver Comet',
  'Ski Ride',
  'Sky Blazer',
  'Sky Chaser',
  'Skyclone',
  'Sky Coaster',
  'Sky King',
  'Skylark',
  'Skyliner',
  'Skyline Twister',
  'Skyrocket',
  'Sky Rocket',
  'Skyrocket Jr.',
  'Skyscraper',
  'Sleigh Ride',
  'Some Kick',
  'Son Of Beast',
  'Souris folle',
  'Speed Hound',
  'Speed-O-Plane',
  'Speed Toboggan',
  'Speedway',
  'Spiral Railway',
  'Stampida',
  'Starliner',
  'Storm',
  'Swamp Fox',
  'Switchback',
  'Switchback Pleasure Railway',
  'Switchback Railway',
  'Switchback Railway ',
  'Szeneriebahn',
  'Tail Spin',
  'Teddy Bear',
  'Texas Cyclone',
  'Texas Giant',
  'Texas Stingray',
  'Texas Tornado',
  'T Express',
  'These United States',
  "Thompson's Scenic Railway",
  "Thompson's Thriller",
  'Thriller',
  'Thunderbird',
  'Thunderbolt',
  'Thundercoaster',
  'Thunder Eagle',
  'Thunderhawk',
  'Thunderhead',
  'Thunder Road',
  'Thunder Run',
  'Timber',
  'Timberhawk: Ride of Prey',
  'Timber Terror',
  'Timber Wolf',
  'Time Travel',
  'Tip of the Tips',
  'Toboggan',
  'Toboggan Coaster',
  'Toboggan Figure 8',
  'Toboggan Racer',
  'Toboggan Slide',
  'Toboggan slide',
  'Tomahawk',
  'Tonnerre 2 Zeus',
  'Top',
  'Topsy Turvy',
  'Tornado',
  'Touring the Alps',
  'Tremors',
  'Tren Panoramico',
  'Triple Eight',
  'Triple Racing Coaster',
  'Trip Thru the Clouds',
  'Trip to the Moon',
  'Trip to the North Pole',
  'Troy',
  'Twisted Twins',
  'Twister',
  'Twister III: Storm Chaser',
  'Underground',
  'U.S. Scenic Railway',
  'Valley Volcano',
  'Velvet Coaster',
  'Velvet Racer',
  'Velvet Toboggan',
  'Villain',
  'Viper',
  'Voyage',
  'Wasserrutschbahn',
  'Werewolf',
  'Whirlwind',
  'Whirl Wind',
  'Whirlwind Dipper',
  'Whirlwind Racer',
  'White Canyon',
  'White City Flyer',
  'White Cyclone',
  'White Flyer',
  'White Lightning',
  'Whiz Bang',
  'Whizzer',
  'Whoopee Baby Scenic',
  'Whoopee Coaster',
  'Wicker Man',
  'Wild Bill',
  'Wildcat',
  'Wild Cat',
  'Wilde Beast',
  'Wild One',
  'Wiz',
  'Wodan Timbur Coaster',
  'Wolverine Wildcat',
  "Wolz's Thriller",
  'Wood Coaster',
  'Wooden Coaster - Fireball',
  'Wooden Dragons Roller Coaster',
  'Wooden Warrior',
  'Wood Express',
  'Woodstock Express',
  "World's Great Scenic Railway",
  'Yankee Cannonball',
  "Zach's Zoomer",
  'Zambezi Zinger',
  'Zephyr',
  'Zephyr Jr.',
  'Zeus',
  'Zingo',
  'Zip',
  'Zipper Dipper',
  'Zippin Pippin',
] as const;
